spring.application:
  name: MyWeb

spring:
  data:
    redis:
      host: redis.kaoxing.top
      port: 6379
      password: 760810Pp!
  datasource:
    url: jdbc:mysql://101.132.96.240:3306/webapp
    username: root
    password: 760810Pp!
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  address: 0.0.0.0
  port: 80

minesweeper:
  remoteServer:
    url: http://py.kaoxing.top:5000
    create: /create
    reset: /reset
    reveal: /reveal
    board: /board
    agentReveal: /agentReveal
    delete: /delete
    password: kaoxing
    tokenExpiration: 3600

UCICourseScan:
  url: https://www.reg.uci.edu/perl/WebSoc


