spring.application:
  name: MyWeb

spring:
  data:
    redis:
      host: redis.kaoxing.top
      port: 6379
  mvc:
    view:
      prefix: /
      suffix: .html


server:
  address: 0.0.0.0
  port: 80

minesweeper:
  remoteServer:
    url: http://py.kaoxing.top:5000
    create: /create
    reset: /reset
    reveal: /reveal
    board: /board
    delete: /delete
    password: kaoxing
    tokenExpiration: 3600

UCICourseScan:
  url: https://www.reg.uci.edu/perl/WebSoc


